const Employees = [
  {
    id: 1,
    name: "John",
    email: "e@e.c",
    password: "123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Update client report",
        description:
          "Prepare and update the quarterly client performance report.",
        date: "2025-01-10",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix login bug",
        description: "Resolve issue causing failed login attempts on mobile.",
        date: "2025-01-04",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Prepare meeting notes",
        description:
          "Meeting notes for the product discussion with management.",
        date: "2025-01-02",
        category: "Communication",
      },
    ],
  },
  {
    id: 2,
    name: "Sophia",
    email: "employee2@example.com",
    password: "password123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Design landing page",
        description: "Create initial UI mockups for the homepage redesign.",
        date: "2025-01-12",
        category: "UI/Design",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Performance optimization",
        description: "Reduce page load time by optimizing images and scripts.",
        date: "2025-01-07",
        category: "Optimization",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team training session",
        description: "Conduct an onboarding training for new interns.",
        date: "2024-12-28",
        category: "Training",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "API data migration",
        description: "Move product data to the new API and verify schema.",
        date: "2025-01-01",
        category: "Backend",
      },
    ],
  },
  {
    id: 3,
    name: "Liam",
    email: "employee3@example.com",
    password: "password123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Inventory update",
        description: "Check and update warehouse product count in system.",
        date: "2025-01-11",
        category: "Data Entry",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Customer ticket resolution",
        description: "Close pending tickets and notify customers.",
        date: "2025-01-05",
        category: "Support",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Supplier call",
        description: "Failed to connect with supplier for restock discussion.",
        date: "2025-01-03",
        category: "Communication",
      },
    ],
  },
  {
    id: 4,
    name: "Ava",
    email: "employee4@example.com",
    password: "password123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "UI bug review",
        description: "Review layout issues in mobile responsive pages.",
        date: "2025-01-09",
        category: "UI/Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Create component library",
        description: "Build reusable UI components for internal use.",
        date: "2024-12-30",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Deploy test build",
        description: "Deployment failed due to configuration issues.",
        date: "2025-01-06",
        category: "Deployment",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Update dependencies",
        description: "Upgrade project packages to latest versions.",
        date: "2025-01-01",
        category: "Maintenance",
      },
    ],
  },
  {
    id: 5,
    name: "Ethan",
    email: "employee5@example.com",
    password: "password123",
    taskCounts: {
      active: 1,
      newTask: 2,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Create analytics dashboard",
        description: "Init dashboard with chart.js for sales tracking.",
        date: "2025-01-14",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Database indexing",
        description: "Improve query speed by adding indexes.",
        date: "2025-01-08",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Email campaign",
        description: "Campaign rejected due to formatting issues.",
        date: "2025-01-04",
        category: "Marketing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Security audit",
        description: "Passed automatic security checks successfully.",
        date: "2024-12-29",
        category: "Security",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "CRM update",
        description: "Add new customer categories to CRM system.",
        date: "2025-01-12",
        category: "Management",
      },
    ],
  },
];

const Admin = [
  {
    id: 101,
    // name: "Admin-Joe",
    email: "admin@example.com",
    password: "password123",
  },
];

export const SetLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(Employees));
  localStorage.setItem("admin", JSON.stringify(Admin));
};
export const GetLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
